export const FEATURED_MANGA = [
  {
    id: '1',
    title: 'Childhood Friend of the Zenith',
    coverImage: 'https://static.wikia.nocookie.net/cfozenith/images/8/89/Gu_Yangcheon.jpg/revision/latest/scale-to-width-down/1000?cb=20240829141330/400x200',
    rating: 9.9,
    genres: ['Action', 'Fantasy', 'Martial Arts', 'Wuxia'],
    summary: 'Gu Yongchun, who betrayed the Orthodox sects, became a demonic human...',
    status: 'Ongoing',
  },
  {
    id: '2',
    title: 'Nano Machine',
    coverImage: 'https://static.wikia.nocookie.net/nano-mashine/images/3/3a/Nano_Machine_Manhwa_Season_2.jpg/revision/latest?cb=20240420230935/400x200',
    rating: 9.6,
    genres: ['Action', 'Martial Arts', 'Sci-Fi'],
    summary: 'After being held in disdain and having his life put in danger, an orphan from the Demonic Cult...',
    status: 'Ongoing',
  },
  {
    id: '3',
    title: 'Legend of the Northern Blade',
    coverImage: 'https://static.wikia.nocookie.net/legend-of-the-northern-blade/images/5/50/Wiki-background/revision/latest?cb=20210216000420',
    rating: 8.8,
    genres: ['Action', 'Adventure', 'Martial Arts'],
    summary: 'When the world was plunged into darkness by the Silent Night, the Martial Arts Alliance...',
    status: 'Ongoing',
  },
  {
    id: '4',
    title: 'Naruto',
    coverImage: 'https://static.wikia.nocookie.net/naruto/images/d/da/Ultimate_Ninja_5.jpg/revision/latest/scale-to-width-down/1000?cb=20130728020710',
    rating: 9.2,
    genres: ['Action', 'Fantasy', 'Martial Arts', 'Wuxia'],
    summary: 'Gu Yongchun, who betrayed the Orthodox sects, became a demonic human...',
    status: 'Ongoing',
  },
  {
    id: '5',
    title: 'One Piece',
    coverImage: 'https://static.wikia.nocookie.net/onepiece/images/8/8a/Volume_96.png/revision/latest/scale-to-width-down/1000?cb=20201201125750',
    rating: 10,
    genres: ['Action', 'Fantasy', 'Martial Arts', 'Wuxia'],
    summary: 'Gu Yongchun, who betrayed the Orthodox sects, became a demonic human...',
    status: 'Ongoing',
  },
  {
    id: '6',
    title: 'Dragon Ball',
    coverImage: 'https://static.wikia.nocookie.net/dragonball/images/b/be/DBS_Vol_11_ENG.jpg/revision/latest/scale-to-width-down/1000?cb=20211218103745',
    rating: 9.6,
    genres: ['Action', 'Fantasy', 'Martial Arts', 'Wuxia'],
    summary: 'Gu Yongchun, who betrayed the Orthodox sects, became a demonic human...',
    status: 'Ongoing',
  },
];

export const POPULAR_MANGA = [
  {
    id: '1',
    title: 'Childhood Friend of the Zenith',
    coverImage: 'https://static.wikia.nocookie.net/cfozenith/images/8/89/Gu_Yangcheon.jpg/revision/latest/scale-to-width-down/1000?cb=20240829141330/300x400',
    chapter: '40',
    rating: 9.8,
  },
  {
    id: '2',
    title: 'Nano Machine',
    coverImage: 'https://static.wikia.nocookie.net/nano-mashine/images/3/3a/Nano_Machine_Manhwa_Season_2.jpg/revision/latest?cb=20240420230935/690x1000',
    chapter: '231',
    rating: 9.2,
  },
  {
    id: '3',
    title: 'The Dark Magician',
    coverImage: 'https://static.wikia.nocookie.net/yonderstory/images/7/74/66666_Years_Advent_of_the_Dark_Mage_3.jpg/revision/latest?cb=20231111130148/300x400',
    chapter: '89',
    rating: 8.6,
  },
  {
    id: '4',
    title: 'One Piece',
    coverImage: 'https://static.wikia.nocookie.net/onepiece/images/8/8a/Volume_96.png/revision/latest/scale-to-width-down/1000?cb=20201201125750/300x400',
    chapter: '156',
    rating: 10,
  },
  {
    id: '5',
    title: 'Return of the Mount Hua Sect',
    coverImage: 'https://static.wikia.nocookie.net/return-of-the-mount-hua-sect/images/d/d4/Webtoon_Cover_art_4.png/revision/latest/scale-to-width-down/200?cb=20230630153517/300x400',
    chapter: '95',
    rating: 9.8,
  },
  {
    id: '6',
    title: 'Legend of Asura',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/0/00/LOATVD.webp/revision/latest?cb=20220718194312',
    chapter: '73',
    rating: 9.4,
  },
  {
    id: '7',
    title: 'Heavenly Demon Chronicles',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/c/c6/HMG.webp/revision/latest?cb=20220718094915',
    chapter: '54',
    rating: 7.8,
  },
  {
    id: '8',
    title: 'Chronicles of the Martial God',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/f/fd/COTMGR.webp/revision/latest?cb=20220717224056',
    chapter: '45',
    rating: 8.3,
  },
  {
    id: '9',
    title: 'Legend of the Northern Blade',
    coverImage: 'https://static.wikia.nocookie.net/legend-of-the-northern-blade/images/5/50/Wiki-background/revision/latest?cb=20210216000420',
    chapter: '152',
    rating: 9.0,
  },
  {
    id: '10',
    title: 'Dragon Ball',
    coverImage: 'https://static.wikia.nocookie.net/dragonball/images/b/be/DBS_Vol_11_ENG.jpg/revision/latest/scale-to-width-down/1000?cb=20211218103745',
    chapter: '322',
    rating: 9.3,
  }
];

export const LATEST_MANGA = [
  {
    id: '1',
    title: 'Return of the Mount Hua Sect',
    coverImage: 'https://static.wikia.nocookie.net/return-of-the-mount-hua-sect/images/d/d4/Webtoon_Cover_art_4.png/revision/latest/scale-to-width-down/200?cb=20230630153517/300x400',
    chapter: '95',
    rating: 9.8,
    updated: '5 mins ago',
  },
  {
    id: '2',
    title: 'Legend of Asura',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/0/00/LOATVD.webp/revision/latest?cb=20220718194312',
    chapter: '73',
    rating: 9.7,
    updated: '10 mins ago',
  },
  {
    id: '3',
    title: 'Heavenly Demon Chronicles',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/c/c6/HMG.webp/revision/latest?cb=20220718094915',
    chapter: '54',
    rating: 9.9,
    updated: '15 mins ago',
  },
  {
    id: '4',
    title: 'Chronicles of the Martial God',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/f/fd/COTMGR.webp/revision/latest?cb=20220717224056',
    chapter: '45',
    rating: 9.6,
    updated: '30 mins ago',
  },
  {
    id: '5',
    title: 'Childhood Friend of the Zenith',
    coverImage: 'https://static.wikia.nocookie.net/cfozenith/images/8/89/Gu_Yangcheon.jpg/revision/latest/scale-to-width-down/1000?cb=20240829141330/300x400',
    chapter: '40',
    rating: 9.9,
    updated: '1 hour ago',
  },
  {
    id: '6',
    title: 'Nano Machine',
    coverImage: 'https://static.wikia.nocookie.net/nano-mashine/images/3/3a/Nano_Machine_Manhwa_Season_2.jpg/revision/latest?cb=20240420230935/690x1000',
    chapter: '231',
    rating: 9.9,
    updated: '2 hours ago',
  },
  {
    id: '7',
    title: 'The Dark Magician',
    coverImage: 'https://static.wikia.nocookie.net/yonderstory/images/7/74/66666_Years_Advent_of_the_Dark_Mage_3.jpg/revision/latest?cb=20231111130148/300x400',
    chapter: '89',
    rating: 9.8,
    updated: '3 hours ago',
  },
  {
    id: '8',
    title: 'One Piece',
    coverImage: 'https://static.wikia.nocookie.net/onepiece/images/8/8a/Volume_96.png/revision/latest/scale-to-width-down/1000?cb=20201201125750/300x400',
    chapter: '956',
    rating: 9.7,
    updated: '4 hours ago',
  },
  {
    id: '9',
    title: 'Legend of the Northern Blade',
    coverImage: 'https://static.wikia.nocookie.net/legend-of-the-northern-blade/images/5/50/Wiki-background/revision/latest?cb=20210216000420',
    chapter: '152',
    rating: 9.7,
    updated: '5 hours ago',
  },
  {
    id: '10',
    title: 'Naruto',
    coverImage: 'https://static.wikia.nocookie.net/naruto/images/d/da/Ultimate_Ninja_5.jpg/revision/latest/scale-to-width-down/1000?cb=20130728020710',
    chapter: '786',
    rating: 9.7,
    updated: '6 hours ago',
  },
  {
    id: '11',
    title: 'One Piece',
    coverImage: 'https://static.wikia.nocookie.net/onepiece/images/8/8a/Volume_96.png/revision/latest/scale-to-width-down/1000?cb=20201201125750',
    chapter: '955',
    rating: 9.7,
    updated: '7 hours ago',
  },
  {
    id: '12',
    title: 'Dragon Ball',
    coverImage: 'https://static.wikia.nocookie.net/dragonball/images/b/be/DBS_Vol_11_ENG.jpg/revision/latest/scale-to-width-down/1000?cb=20211218103745',
    chapter: '322',
    rating: 9.7,
    updated: '8 hours ago',
  },
];
export const Manga = [
  {
    id: '1',
    title: 'Return of the Mount Hua Sect',
    coverImage: 'https://static.wikia.nocookie.net/return-of-the-mount-hua-sect/images/d/d4/Webtoon_Cover_art_4.png/revision/latest/scale-to-width-down/200?cb=20230630153517/300x400',
    chapter: '95',
    rating: 9.8,
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    updated: '5 mins ago',
    status: 'Ongoing',
  },
  {
    id: '2',
    title: 'Legend of Asura',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/0/00/LOATVD.webp/revision/latest?cb=20220718194312',
    chapter: '73',
    rating: 9.7,
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    updated: '10 mins ago',
    status: 'Ongoing',
  },
  {
    id: '3',
    title: 'Heavenly Demon Chronicles',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/c/c6/HMG.webp/revision/latest?cb=20220718094915',
    chapter: '54',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.9,
    updated: '15 mins ago',
    status: 'Ongoing',
  },
  {
    id: '4',
    title: 'Chronicles of the Martial God',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/f/fd/COTMGR.webp/revision/latest?cb=20220717224056',
    chapter: '45',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.6,
    updated: '30 mins ago',
    status: 'Ongoing',
  },
  {
    id: '5',
    title: 'Childhood Friend of the Zenith',
    coverImage: 'https://static.wikia.nocookie.net/cfozenith/images/8/89/Gu_Yangcheon.jpg/revision/latest/scale-to-width-down/1000?cb=20240829141330/300x400',
    chapter: '40',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.9,
    updated: '1 hour ago',
    status: 'Ongoing',
  },
  {
    id: '6',
    title: 'Nano Machine',
    coverImage: 'https://static.wikia.nocookie.net/nano-mashine/images/3/3a/Nano_Machine_Manhwa_Season_2.jpg/revision/latest?cb=20240420230935/690x1000',
    chapter: '231',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.9,
    updated: '2 hours ago',
    status: 'Ongoing',
  },
  {
    id: '7',
    title: 'The Dark Magician',
    coverImage: 'https://static.wikia.nocookie.net/yonderstory/images/7/74/66666_Years_Advent_of_the_Dark_Mage_3.jpg/revision/latest?cb=20231111130148/300x400',
    chapter: '89',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.8,
    updated: '3 hours ago',
    status: 'Ongoing',
  },
  {
    id: '8',
    title: 'One Piece',
    coverImage: 'https://static.wikia.nocookie.net/onepiece/images/8/8a/Volume_96.png/revision/latest/scale-to-width-down/1000?cb=20201201125750/300x400',
    chapter: '956',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.7,
    updated: '4 hours ago',
    status: 'Ongoing',
  },
  {
    id: '9',
    title: 'Legend of the Northern Blade',
    coverImage: 'https://static.wikia.nocookie.net/legend-of-the-northern-blade/images/5/50/Wiki-background/revision/latest?cb=20210216000420',
    chapter: '152',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.7,
    updated: '5 hours ago',
    status: 'Ongoing',
  },
  {
    id: '10',
    title: 'Naruto',
    coverImage: 'https://static.wikia.nocookie.net/naruto/images/d/da/Ultimate_Ninja_5.jpg/revision/latest/scale-to-width-down/1000?cb=20130728020710',
    chapter: '786',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.7,
    updated: '6 hours ago',
    status: 'Ongoing',
  },
  {
    id: '11',
    title: 'One Piece',
    coverImage: 'https://static.wikia.nocookie.net/onepiece/images/8/8a/Volume_96.png/revision/latest/scale-to-width-down/1000?cb=20201201125750',
    chapter: '955',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.7,
    updated: '7 hours ago',
    status: 'Ongoing',
  },
  {
    id: '12',
    title: 'Dragon Ball',
    coverImage: 'https://static.wikia.nocookie.net/dragonball/images/b/be/DBS_Vol_11_ENG.jpg/revision/latest/scale-to-width-down/1000?cb=20211218103745',
    chapter: '322',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.7,
    updated: '8 hours ago',
    status: 'Ongoing',
  },
  {
    id: '13',
    title: 'Childhood Friend of the Zenith',
    coverImage: 'https://static.wikia.nocookie.net/cfozenith/images/8/89/Gu_Yangcheon.jpg/revision/latest/scale-to-width-down/1000?cb=20240829141330/300x400',
    chapter: '40',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.8,
    status: 'Ongoing',
  },
  {
    id: '14',
    title: 'Nano Machine',
    coverImage: 'https://static.wikia.nocookie.net/nano-mashine/images/3/3a/Nano_Machine_Manhwa_Season_2.jpg/revision/latest?cb=20240420230935/690x1000',
    chapter: '231',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.2,
    status: 'Ongoing',
  },
  {
    id: '15',
    title: 'The Dark Magician',
    coverImage: 'https://static.wikia.nocookie.net/yonderstory/images/7/74/66666_Years_Advent_of_the_Dark_Mage_3.jpg/revision/latest?cb=20231111130148/300x400',
    chapter: '89',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 8.6,
    status: 'Ongoing',
  },
  {
    id: '16',
    title: 'One Piece',
    coverImage: 'https://static.wikia.nocookie.net/onepiece/images/8/8a/Volume_96.png/revision/latest/scale-to-width-down/1000?cb=20201201125750/300x400',
    chapter: '156',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 10,
    status: 'Ongoing',
  },
  {
    id: '17',
    title: 'Return of the Mount Hua Sect',
    coverImage: 'https://static.wikia.nocookie.net/return-of-the-mount-hua-sect/images/d/d4/Webtoon_Cover_art_4.png/revision/latest/scale-to-width-down/200?cb=20230630153517/300x400',
    chapter: '95',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.8,
    status: 'Ongoing',
  },
  {
    id: '18',
    title: 'Legend of Asura',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/0/00/LOATVD.webp/revision/latest?cb=20220718194312',
    chapter: '73',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.4,
    status: 'Ongoing',
  },
  {
    id: '19',
    title: 'Heavenly Demon Chronicles',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/c/c6/HMG.webp/revision/latest?cb=20220718094915',
    chapter: '54',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 7.8,
    status: 'Ongoing',
  },
  {
    id: '20',
    title: 'Chronicles of the Martial God',
    coverImage: 'https://static.wikia.nocookie.net/asurascans/images/f/fd/COTMGR.webp/revision/latest?cb=20220717224056',
    chapter: '45',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 8.3,
    status: 'Ongoing',
  },
  {
    id: '21',
    title: 'Legend of the Northern Blade',
    coverImage: 'https://static.wikia.nocookie.net/legend-of-the-northern-blade/images/5/50/Wiki-background/revision/latest?cb=20210216000420',
    chapter: '152',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.0,
    status: 'Ongoing',
  },
  {
    id: '22',
    title: 'Dragon Ball',
    coverImage: 'https://static.wikia.nocookie.net/dragonball/images/b/be/DBS_Vol_11_ENG.jpg/revision/latest/scale-to-width-down/1000?cb=20211218103745',
    chapter: '322',
    summary: 'The story follows the return of the Mount Hua Sect, a powerful and ancient martial arts organization',
    rating: 9.3,
    status: 'Ongoing',
  }
];